theme:
  name: material

site_name: FlashSim

site_url: https://francesco-vaselli.github.io/nfs/

nav:
    - Home: index.md
    - Preprocessing: preprocessing.md
    - Trainings: trainings.md
    - Generation: generation.md
    - Results: results.md
    - About: about.md
