theme:
  name: material
  icon:
    repo: fontawesome/brands/github 

site_name: FlashSim

site_url: https://francesco-vaselli.github.io/nfs/

nav:
    - Home: index.md
    - Preprocessing: preprocessing.md
    - Trainings: trainings.md
    - Generation: generation.md
    - Results: results.md
    - About: about.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

repo_url: https://github.com/francesco-vaselli/FlashSim
repo_name: francesco-vaselli/FlashSim
edit_uri: ""

  
